// =============================================================================
// Palm_left_V2.scad  —  e-NABLE Phoenix palm, parametric reconstruction
// =============================================================================
// Method: RECONSTRUCTION_METHOD.md (feature-fidelity + ghost, measure-never-guess).
// Features + finger linkages measured by parallel agents; simple primitives,
// fuse+subtract. Frame: original recentred X/Y-centred, Z min -> 0 (on plate).
// Aligned ghost: output/orig_aligned.stl. Original bbox X +-41.43, Y +-46, Z 0..30.6.
//
// SINGLE-FILE build: the former part includes (shell / thumb / rings / fins /
// wrist back) are now fused inline as clearly marked PART sections below, each
// with its own show_* checkbox in the Customizer [Features] tab so any part can
// be switched off independently. model() unions every enabled part; global pin
// bores / cable channels are cut per part.
//
// Verification harness (Customizer): show_ghost overlays the original STL;
// section + section_at slice both model and ghost so you can read the interior.
// =============================================================================

include <BOSL2/std.scad>
$fn = 48;

/* [Display] */
show_ghost  = false;    // overlay the original STL as a transparent ghost
ghost_color = "SkyBlue";// ghost tint (color name or [r,g,b])
ghost_alpha = 0.35;     // ghost opacity 0 (invisible) .. 1 (opaque)

/* [Section] */
section = "off";        // [off, longitudinal, transverse, horizontal]
section_at = 0;         // [-50:0.5:50]

/* [Features] */
show_shell      = true;   // dorsal shell: regularised arch + cable channels
show_knuckles   = true;   // finger pivot clevises + dome<->clevis junction
show_fins       = true;   // dorsal shark-fin blades + crown caps
show_thumb      = true;   // thumb pivot mount (lug + bores)
show_wrist      = true;   // wrist hinge ears + gauntlet side walls
show_wrist_back = true;   // gauntlet back wall (ghost-clip band)
show_grid       = true;   // perforated palmar floor + vent grid
debug_colors    = false;  // colour each part distinctly (see what's what); else solid yellow

/* [Hidden] */
ghost_dir = "/home/pec/dev/openscad-parametric-reconstructor/tmp/openscad-projects/palm-left-reconstructed/output";
ghost_stl = str(ghost_dir, "/orig_aligned.stl");

// =============================================================================
// PART 1 — DORSAL SHELL                                        [show_shell]
// -----------------------------------------------------------------------------
//  Thin arch shell (open underneath) + 5 internal cable channels.
//  Outer silhouette within ~1.25 mm of the approved V2 shell.
//
//  How it builds: lofts (BOSL2 skin) the OUTER arch through 7 Y stations
//  to a solid dome, then subtracts a second loft of the SAME arch offset
//  inward by WALL to hollow it (open bottom), then subtracts the 5 cable
//  channels as swept tubes. -> dorsal_shell()
// =============================================================================

/* ---- HEADLINE EDITABLE PARAMETERS ---- */
WALL       = 5.0;    // shell wall thickness (mm)  [4.6 measured; 5.0 covers mid-roof underfill]
CH_R       = 1.23;   // cable-channel bore radius (Ø2.3 mm measured)
APEX_GAIN  = 1.0;    // scale all apex heights (1.0 = as-measured ~30.6 mm)
SPAN_GAIN  = 1.0;    // scale arch half-width about its centre

/* ---- OUTER ARCH SILHOUETTE ----------------------------------------
   AY = the Y of each cross-section station (wrist rim -> finger rim).
   AP = one 10-point arch polygon per station (X,Z in that Y-plane):
        footL, kneeL, 6 broad-top points, kneeR, footR  (feet on plate z=0).
   Edit a station's apex by raising its centre z; edit span via foot x.
   NOTE: these arrays are regenerated by a separate fitting pass — do not
   hand-edit the numbers here. */
AY = [-30.00, -28.17, -26.34, -24.52, -22.69, -20.86, -19.03, -17.21, -15.38, -13.55, -11.72, -9.90, -8.07, -6.24, -4.41, -2.59, -0.76, 1.07, 2.90, 4.72, 6.55, 8.38, 10.21, 12.03, 13.86, 15.69, 17.52, 19.34, 21.17, 23.00];
AP = [
  [[-38.47,0.00],[-38.47,3.34],[-38.47,6.67],[-38.47,10.01],[-38.47,13.34],[-38.47,16.68],[-38.47,20.01],[-36.27,21.49],[-35.05,23.98],[-31.98,24.83],[-29.15,26.21],[-26.01,27.03],[-22.74,27.46],[-19.54,27.91],[-16.47,29.14],[-13.14,29.30],[-9.81,29.32],[-6.47,29.32],[-3.14,29.31],[0.20,29.22],[3.44,28.64],[6.34,27.46],[9.56,27.10],[12.52,25.89],[15.60,25.30],[18.40,23.69],[21.13,22.23],[23.05,20.01],[23.05,16.68],[23.05,13.34],[23.05,10.01],[23.05,6.67],[23.05,3.34],[23.05,0.00]],
  [[-38.88,0.00],[-38.88,3.30],[-38.88,6.60],[-38.88,9.90],[-38.88,13.20],[-38.88,16.49],[-38.88,19.79],[-37.52,22.64],[-34.98,24.70],[-32.09,26.26],[-29.03,27.42],[-25.84,28.25],[-22.61,28.92],[-19.36,29.48],[-16.11,30.00],[-12.86,30.52],[-9.56,30.59],[-6.26,30.59],[-2.96,30.49],[0.28,30.02],[3.55,29.58],[6.77,28.96],[9.99,28.28],[13.15,27.45],[16.24,26.36],[19.12,24.79],[21.55,22.60],[23.05,19.79],[23.05,16.49],[23.05,13.20],[23.05,9.90],[23.05,6.60],[23.05,3.30],[23.05,0.00]],
  [[-39.30,0.00],[-39.30,3.33],[-39.30,6.65],[-39.30,9.98],[-39.30,13.31],[-39.30,16.63],[-39.30,19.96],[-37.74,22.71],[-35.27,24.86],[-32.37,26.36],[-29.31,27.41],[-26.12,28.16],[-22.94,28.87],[-19.72,29.45],[-16.46,29.99],[-13.19,30.43],[-9.88,30.62],[-6.55,30.63],[-3.23,30.54],[0.06,30.15],[3.29,29.53],[6.52,29.00],[9.73,28.33],[12.89,27.47],[15.96,26.39],[18.85,24.82],[21.30,22.67],[23.05,19.96],[23.05,16.63],[23.05,13.31],[23.05,9.98],[23.05,6.65],[23.05,3.33],[23.05,0.00]],
  [[-39.71,0.00],[-39.71,3.35],[-39.71,6.70],[-39.71,10.05],[-39.71,13.40],[-39.71,16.75],[-39.71,20.10],[-38.22,22.94],[-35.84,25.23],[-32.82,26.38],[-29.73,27.43],[-26.55,28.31],[-23.32,28.88],[-20.06,29.46],[-16.78,29.98],[-13.49,30.43],[-10.16,30.63],[-6.81,30.64],[-3.47,30.50],[-0.15,30.14],[3.08,29.48],[6.36,29.06],[9.61,28.43],[12.78,27.47],[15.90,26.55],[18.79,25.04],[21.27,22.87],[23.05,20.10],[23.05,16.75],[23.05,13.40],[23.05,10.05],[23.05,6.70],[23.05,3.35],[23.05,0.00]],
  [[-40.13,0.00],[-40.13,3.36],[-40.13,6.71],[-40.13,10.07],[-40.13,13.42],[-40.13,16.78],[-40.13,20.14],[-38.78,23.01],[-36.24,25.16],[-33.37,26.86],[-30.09,27.42],[-26.88,28.31],[-23.63,28.96],[-20.34,29.41],[-17.05,29.94],[-13.73,30.39],[-10.39,30.61],[-7.03,30.63],[-3.68,30.57],[-0.38,30.11],[2.89,29.61],[6.18,29.08],[9.45,28.41],[12.71,27.70],[15.84,26.59],[18.79,25.08],[21.33,22.93],[23.05,20.14],[23.05,16.78],[23.05,13.42],[23.05,10.07],[23.05,6.71],[23.05,3.36],[23.05,0.00]],
  [[-40.13,0.00],[-40.13,3.37],[-40.13,6.74],[-40.13,10.11],[-40.13,13.48],[-40.13,16.85],[-40.13,20.22],[-39.10,23.22],[-36.65,25.46],[-33.54,26.57],[-30.33,27.42],[-27.07,28.19],[-23.77,28.85],[-20.45,29.38],[-17.13,29.89],[-13.80,30.31],[-10.45,30.55],[-7.08,30.56],[-3.71,30.50],[-0.38,30.09],[2.96,29.62],[6.25,29.06],[9.54,28.38],[12.79,27.55],[15.92,26.50],[18.87,24.99],[21.47,22.90],[23.46,20.22],[23.46,16.85],[23.46,13.48],[23.46,10.11],[23.46,6.74],[23.46,3.37],[23.46,0.00]],
  [[-40.55,0.00],[-40.55,3.39],[-40.55,6.78],[-40.55,10.16],[-40.55,13.55],[-40.55,16.94],[-40.55,20.33],[-39.31,23.25],[-36.78,25.43],[-33.63,26.60],[-30.48,27.51],[-27.18,28.19],[-23.87,28.82],[-20.54,29.33],[-17.19,29.77],[-13.84,30.18],[-10.47,30.43],[-7.08,30.46],[-3.69,30.40],[-0.33,30.08],[2.98,29.57],[6.24,29.00],[9.54,28.34],[12.78,27.51],[15.95,26.45],[18.96,24.92],[21.61,22.86],[23.75,20.29],[23.88,16.94],[23.88,13.55],[23.88,10.16],[23.88,6.78],[23.88,3.39],[23.88,0.00]],
  [[-40.55,0.00],[-40.55,3.40],[-40.55,6.80],[-40.55,10.20],[-40.55,13.60],[-40.55,17.00],[-40.55,20.40],[-39.44,23.39],[-36.74,25.38],[-33.63,26.64],[-30.41,27.47],[-27.13,28.19],[-23.80,28.74],[-20.47,29.23],[-17.13,29.65],[-13.76,30.05],[-10.37,30.30],[-6.97,30.33],[-3.57,30.28],[-0.20,29.94],[3.15,29.52],[6.40,28.82],[9.74,28.25],[12.94,27.33],[16.13,26.28],[19.09,24.76],[21.80,22.79],[24.09,20.34],[24.29,17.00],[24.29,13.60],[24.29,10.20],[24.29,6.80],[24.29,3.40],[24.29,0.00]],
  [[-40.55,0.00],[-40.55,3.41],[-40.55,6.81],[-40.55,10.22],[-40.55,13.62],[-40.55,17.03],[-40.55,20.44],[-39.50,23.46],[-36.72,25.36],[-33.59,26.51],[-30.34,27.39],[-27.08,28.11],[-23.74,28.70],[-20.40,29.15],[-17.04,29.61],[-13.67,29.94],[-10.27,30.15],[-6.87,30.21],[-3.46,30.18],[-0.07,29.93],[3.25,29.48],[6.56,28.81],[9.87,28.18],[13.11,27.30],[16.22,26.14],[19.23,24.72],[21.77,22.67],[24.29,20.44],[24.29,17.03],[24.29,13.62],[24.29,10.22],[24.29,6.81],[24.29,3.41],[24.29,0.00]],
  [[-40.96,0.00],[-40.96,3.40],[-40.96,6.79],[-40.96,10.19],[-40.96,13.59],[-40.96,16.98],[-40.96,20.38],[-39.81,23.38],[-37.12,25.42],[-33.93,26.54],[-30.65,27.37],[-27.32,28.04],[-23.99,28.69],[-20.62,29.14],[-17.25,29.52],[-13.87,29.85],[-10.48,30.06],[-7.09,30.11],[-3.69,30.08],[-0.30,29.85],[3.06,29.41],[6.41,28.91],[9.72,28.18],[12.98,27.29],[16.21,26.28],[19.19,24.73],[21.87,22.67],[24.29,20.38],[24.29,16.98],[24.29,13.59],[24.29,10.19],[24.29,6.79],[24.29,3.40],[24.29,0.00]],
  [[-40.96,0.00],[-40.96,3.40],[-40.96,6.81],[-40.96,10.21],[-40.96,13.61],[-40.96,17.01],[-40.96,20.42],[-40.00,23.45],[-37.27,25.45],[-34.10,26.62],[-30.78,27.36],[-27.44,27.99],[-24.10,28.62],[-20.74,29.13],[-17.36,29.49],[-13.98,29.81],[-10.58,30.01],[-7.18,30.05],[-3.78,30.01],[-0.38,29.78],[2.98,29.40],[6.33,28.84],[9.64,28.21],[12.90,27.29],[16.12,26.26],[19.12,24.71],[21.82,22.68],[24.29,20.42],[24.29,17.01],[24.29,13.61],[24.29,10.21],[24.29,6.81],[24.29,3.40],[24.29,0.00]],
  [[-41.38,0.00],[-41.38,3.41],[-41.38,6.82],[-41.38,10.24],[-41.38,13.65],[-41.38,17.06],[-41.38,20.47],[-40.25,23.49],[-37.47,25.37],[-34.34,26.65],[-31.00,27.34],[-27.65,28.00],[-24.31,28.58],[-20.95,29.13],[-17.55,29.47],[-14.16,29.81],[-10.75,29.98],[-7.34,30.01],[-3.93,29.96],[-0.52,29.73],[2.86,29.38],[6.23,28.86],[9.51,28.12],[12.80,27.28],[16.04,26.25],[18.96,24.58],[21.66,22.59],[24.29,20.47],[24.29,17.06],[24.29,13.65],[24.29,10.24],[24.29,6.82],[24.29,3.41],[24.29,0.00]],
  [[-41.38,0.00],[-41.38,3.41],[-41.38,6.83],[-41.38,10.24],[-41.38,13.66],[-41.38,17.07],[-41.38,20.48],[-40.26,23.50],[-37.45,25.37],[-34.33,26.66],[-31.00,27.37],[-27.64,27.99],[-24.29,28.56],[-20.94,29.13],[-17.55,29.46],[-14.17,29.83],[-10.76,29.96],[-7.34,29.98],[-3.93,29.91],[-0.52,29.70],[2.85,29.30],[6.21,28.87],[9.48,28.07],[12.74,27.20],[15.95,26.17],[18.90,24.56],[21.46,22.43],[24.15,20.40],[24.29,17.07],[24.29,13.66],[24.29,10.24],[24.29,6.83],[24.29,3.41],[24.29,0.00]],
  [[-41.38,0.00],[-41.38,3.40],[-41.38,6.79],[-41.38,10.19],[-41.38,13.59],[-41.38,16.99],[-41.38,20.38],[-40.16,23.36],[-37.41,25.29],[-34.28,26.55],[-30.97,27.30],[-27.63,27.93],[-24.29,28.50],[-20.95,29.08],[-17.58,29.50],[-14.20,29.83],[-10.81,29.93],[-7.41,29.95],[-4.01,29.88],[-0.62,29.66],[2.75,29.30],[6.09,28.74],[9.40,28.01],[12.68,27.17],[15.80,25.92],[18.75,24.28],[21.51,22.32],[24.27,20.37],[24.29,16.99],[24.29,13.59],[24.29,10.19],[24.29,6.79],[24.29,3.40],[24.29,0.00]],
  [[-41.38,0.00],[-41.38,3.40],[-41.38,6.80],[-41.38,10.20],[-41.38,13.60],[-41.38,17.01],[-41.38,20.41],[-39.80,23.26],[-37.09,25.16],[-33.98,26.46],[-30.67,27.19],[-27.34,27.80],[-24.06,28.54],[-20.72,29.09],[-17.37,29.57],[-13.98,29.83],[-10.58,29.92],[-7.18,29.95],[-3.78,29.86],[-0.40,29.60],[2.96,29.23],[6.29,28.69],[9.60,27.98],[12.82,27.04],[15.89,25.79],[18.61,24.20],[21.44,22.36],[24.07,20.29],[24.29,17.01],[24.29,13.60],[24.29,10.20],[24.29,6.80],[24.29,3.40],[24.29,0.00]],
  [[-40.96,0.00],[-40.96,3.41],[-40.96,6.82],[-40.96,10.23],[-40.96,13.63],[-40.96,17.04],[-40.96,20.45],[-39.39,23.27],[-36.64,25.24],[-33.46,26.42],[-30.15,27.18],[-26.81,27.84],[-23.48,28.54],[-20.15,29.16],[-16.78,29.62],[-13.38,29.83],[-9.97,29.94],[-6.57,29.95],[-3.16,29.87],[0.23,29.56],[3.60,29.15],[6.94,28.60],[10.25,27.88],[13.45,26.82],[16.56,25.46],[18.38,23.41],[21.39,22.28],[23.97,20.25],[24.29,17.04],[24.29,13.63],[24.29,10.23],[24.29,6.82],[24.29,3.41],[24.29,0.00]],
  [[-40.55,0.00],[-40.55,3.39],[-40.55,6.78],[-40.55,10.18],[-40.55,13.57],[-40.55,16.96],[-40.55,20.35],[-39.15,23.23],[-36.38,25.10],[-33.20,26.23],[-29.90,26.98],[-26.62,27.68],[-23.33,28.42],[-20.04,29.12],[-16.69,29.57],[-13.31,29.80],[-9.92,29.95],[-6.53,29.97],[-3.14,29.89],[0.23,29.64],[3.58,29.22],[6.93,28.69],[10.22,27.92],[13.44,26.92],[16.58,25.68],[18.39,23.25],[21.27,22.07],[23.97,20.17],[24.29,16.96],[24.29,13.57],[24.29,10.18],[24.29,6.78],[24.29,3.39],[24.29,0.00]],
  [[-40.55,0.00],[-40.55,3.32],[-40.55,6.63],[-40.55,9.95],[-40.55,13.26],[-40.55,16.58],[-40.55,19.89],[-39.21,22.65],[-36.58,24.61],[-33.51,25.83],[-30.29,26.56],[-27.07,27.27],[-23.87,28.08],[-20.64,28.78],[-17.39,29.35],[-14.09,29.67],[-10.79,29.88],[-7.47,29.93],[-4.16,29.92],[-0.85,29.76],[2.44,29.41],[5.72,28.97],[8.96,28.30],[12.15,27.45],[15.28,26.40],[18.23,24.92],[20.74,22.80],[21.80,19.89],[21.80,16.58],[21.80,13.26],[21.80,9.95],[21.80,6.63],[21.80,3.32],[21.80,0.00]],
  [[-40.55,0.00],[-40.55,3.31],[-40.55,6.62],[-40.55,9.93],[-40.55,13.24],[-40.55,16.55],[-40.55,19.86],[-39.00,22.52],[-36.25,24.31],[-33.17,25.49],[-29.94,26.20],[-26.73,26.96],[-23.52,27.76],[-20.32,28.55],[-17.08,29.17],[-13.79,29.56],[-10.49,29.77],[-7.18,29.85],[-3.87,29.84],[-0.56,29.73],[2.73,29.44],[5.99,28.93],[9.21,28.19],[12.40,27.34],[15.51,26.28],[18.45,24.77],[21.04,22.74],[22.21,19.86],[22.21,16.55],[22.21,13.24],[22.21,9.93],[22.21,6.62],[22.21,3.31],[22.21,0.00]],
  [[-40.13,0.00],[-40.13,3.32],[-40.13,6.64],[-40.13,9.97],[-40.13,13.29],[-40.13,16.61],[-40.13,19.93],[-38.42,22.46],[-35.59,24.14],[-32.43,25.14],[-29.20,25.89],[-25.99,26.67],[-22.78,27.51],[-19.57,28.31],[-16.33,28.99],[-13.05,29.44],[-9.73,29.65],[-6.41,29.73],[-3.09,29.71],[0.23,29.64],[3.54,29.35],[6.80,28.77],[10.01,27.94],[13.18,27.02],[16.28,25.85],[19.16,24.22],[21.73,22.14],[24.07,19.81],[24.29,16.61],[24.29,13.29],[24.29,9.97],[24.29,6.64],[24.29,3.32],[24.29,0.00]],
  [[-40.13,0.00],[-40.13,3.31],[-40.13,6.62],[-40.13,9.93],[-40.13,13.24],[-40.13,16.55],[-40.13,19.86],[-37.98,22.26],[-35.07,23.79],[-31.91,24.70],[-28.69,25.42],[-25.50,26.24],[-22.35,27.12],[-19.22,28.10],[-15.99,28.72],[-12.76,29.34],[-9.45,29.50],[-6.14,29.58],[-2.83,29.58],[0.48,29.50],[3.78,29.36],[7.01,28.72],[10.14,27.81],[13.23,26.86],[16.27,25.73],[19.09,24.07],[21.78,22.19],[24.00,19.76],[24.29,16.55],[24.29,13.24],[24.29,9.93],[24.29,6.62],[24.29,3.31],[24.29,0.00]],
  [[-39.71,0.00],[-39.71,3.28],[-39.71,6.56],[-39.71,9.84],[-39.71,13.12],[-39.71,16.40],[-39.71,19.68],[-37.33,21.88],[-34.43,23.34],[-31.31,24.29],[-28.13,25.06],[-24.98,25.88],[-21.87,26.83],[-18.73,27.64],[-15.59,28.49],[-12.38,29.15],[-9.12,29.41],[-5.84,29.44],[-2.56,29.43],[0.71,29.31],[3.98,29.09],[7.20,28.60],[10.35,27.80],[13.40,26.77],[16.38,25.53],[19.22,23.94],[21.81,21.95],[24.04,19.58],[24.29,16.40],[24.29,13.12],[24.29,9.84],[24.29,6.56],[24.29,3.28],[24.29,0.00]],
  [[-39.30,0.00],[-39.30,3.24],[-39.30,6.49],[-39.30,9.73],[-39.30,12.98],[-39.30,16.22],[-38.99,19.30],[-36.57,21.40],[-33.69,22.84],[-30.62,23.83],[-27.50,24.68],[-24.42,25.59],[-21.34,26.49],[-18.26,27.42],[-15.15,28.31],[-11.98,28.95],[-8.77,29.29],[-5.52,29.33],[-2.28,29.25],[0.96,29.08],[4.19,28.83],[7.38,28.37],[10.50,27.55],[13.54,26.52],[16.52,25.34],[19.31,23.72],[21.94,21.85],[24.05,19.41],[24.29,16.22],[24.29,12.98],[24.29,9.73],[24.29,6.49],[24.29,3.24],[24.29,0.00]],
  [[-39.30,0.00],[-39.30,3.20],[-39.30,6.41],[-39.30,9.61],[-39.30,12.81],[-39.30,16.01],[-38.28,18.83],[-35.78,20.82],[-32.95,22.29],[-29.93,23.30],[-26.83,24.11],[-23.76,24.99],[-20.76,26.06],[-17.73,27.05],[-14.65,27.89],[-11.54,28.61],[-8.39,29.11],[-5.18,29.18],[-1.98,29.09],[1.21,28.85],[4.38,28.43],[7.53,27.93],[10.64,27.20],[13.65,26.21],[16.56,24.96],[19.32,23.37],[21.87,21.47],[24.01,19.14],[24.29,16.01],[24.29,12.81],[24.29,9.61],[24.29,6.41],[24.29,3.20],[24.29,0.00]],
  [[-38.88,0.00],[-38.88,3.16],[-38.88,6.32],[-38.88,9.48],[-38.88,12.63],[-38.88,15.79],[-37.37,18.46],[-34.81,20.31],[-31.99,21.72],[-29.02,22.75],[-26.02,23.71],[-22.99,24.56],[-20.05,25.60],[-17.11,26.71],[-14.09,27.57],[-11.03,28.29],[-7.93,28.80],[-4.78,28.97],[-1.63,28.88],[1.51,28.53],[4.60,28.00],[7.69,27.51],[10.69,26.74],[13.70,25.83],[16.59,24.58],[19.31,23.05],[21.83,21.18],[23.95,18.87],[24.29,15.79],[24.29,12.63],[24.29,9.48],[24.29,6.32],[24.29,3.16],[24.29,0.00]],
  [[-38.47,0.00],[-38.47,3.13],[-38.47,6.26],[-38.47,9.40],[-38.47,12.53],[-38.35,15.63],[-36.45,18.09],[-33.82,19.74],[-31.02,21.09],[-28.28,22.08],[-25.29,23.00],[-22.38,23.96],[-19.47,24.92],[-16.67,26.11],[-13.79,27.15],[-10.81,28.05],[-7.73,28.50],[-4.60,28.65],[-1.47,28.60],[1.62,28.21],[4.73,27.90],[7.66,26.97],[10.71,26.47],[13.61,25.45],[16.45,24.20],[19.24,22.90],[21.63,20.93],[23.69,18.60],[24.29,15.66],[24.29,12.53],[24.29,9.40],[24.29,6.26],[24.29,3.13],[24.29,0.00]],
  [[-38.05,0.00],[-38.05,3.08],[-38.05,6.15],[-38.05,9.23],[-38.05,12.30],[-37.91,15.31],[-35.77,17.49],[-33.20,19.16],[-30.35,20.20],[-27.86,21.31],[-24.94,22.25],[-22.06,23.29],[-19.19,24.33],[-16.37,25.50],[-13.46,26.44],[-10.55,27.39],[-7.52,27.90],[-4.47,28.20],[-1.39,28.19],[1.66,27.81],[4.65,27.14],[7.65,26.57],[10.59,25.71],[13.50,24.81],[16.32,23.63],[19.07,22.27],[21.55,20.48],[23.69,18.30],[24.29,15.38],[24.29,12.30],[24.29,9.23],[24.29,6.15],[24.29,3.08],[24.29,0.00]],
  [[-37.64,0.00],[-37.64,3.03],[-37.64,6.06],[-37.64,9.09],[-37.64,12.12],[-37.47,15.08],[-35.20,17.06],[-32.63,18.64],[-29.74,19.30],[-27.31,20.59],[-24.43,21.52],[-21.60,22.57],[-18.78,23.61],[-15.99,24.73],[-13.18,25.81],[-10.33,26.77],[-7.36,27.35],[-4.35,27.64],[-1.32,27.65],[1.68,27.31],[4.63,26.68],[7.57,26.04],[10.44,25.14],[13.31,24.28],[16.12,23.18],[18.77,21.78],[21.23,20.10],[23.42,18.02],[23.88,15.14],[23.88,12.12],[23.88,9.09],[23.88,6.06],[23.88,3.03],[23.88,0.00]],
  [[-37.22,0.00],[-37.22,2.99],[-37.22,5.98],[-37.22,8.98],[-37.22,11.97],[-37.03,14.90],[-34.70,16.73],[-32.12,18.18],[-29.58,19.33],[-26.68,19.90],[-23.83,20.80],[-21.04,21.87],[-18.32,22.95],[-15.74,23.89],[-13.06,25.02],[-10.29,26.09],[-7.38,26.73],[-4.40,27.02],[-1.41,27.03],[1.56,26.73],[4.49,26.14],[7.39,25.50],[10.28,24.80],[13.07,23.80],[15.84,22.69],[18.43,21.28],[20.90,19.71],[23.08,17.69],[23.88,14.96],[23.88,11.97],[23.88,8.98],[23.88,5.98],[23.88,2.99],[23.88,0.00]],
  [[-36.80,0.00],[-36.80,2.98],[-36.80,5.96],[-36.80,8.94],[-36.80,11.92],[-36.60,14.83],[-34.11,16.40],[-32.37,18.31],[-29.94,19.15],[-26.96,19.26],[-24.05,19.77],[-21.26,20.80],[-18.54,21.90],[-15.67,22.43],[-13.46,23.98],[-10.73,25.09],[-7.90,25.95],[-4.95,26.28],[-1.97,26.30],[1.00,26.10],[3.93,25.62],[6.78,24.88],[9.63,24.14],[12.38,23.35],[15.09,22.24],[17.77,21.07],[20.20,19.40],[22.41,17.50],[23.46,14.90],[23.46,11.92],[23.46,8.94],[23.46,5.96],[23.46,2.98],[23.46,0.00]]
];

/* ---- CABLE CHANNELS (internal, wrist -> finger) -------------------
   5 round bores Ø2.3 mm embedded in the dome roof. Each is a centreline
   polyline [x,y,z]; subtracted as a swept tube of radius CH_R.        */
CH = [
  [[-22.9,-32,24.5],[-22.9,-29,25.3],[-25.0,-12,25.8],[-26.6,-1,24.7],[-27.7,12,20.8],[-28.7,20,16.7],[-29.2,23,15.2],[-29.4,26.5,14.8]],  // ch1 pinky (wrist->finger cap)
  [[-15.3,-32,25.8],[-15.3,-30,25.8],[-15.2,-12,27.1],[-15.0,0,26.5],[-15.0,12,24.4],[-14.9,20,21.9],[-14.9,24,20.0],[-14.9,26.5,19.9]],     // ch2 ring
  [[ -7.5,-32,26.0],[ -7.5,-29,27.1],[ -5.6,-12,27.5],[ -4.3,0,27.2],[ -2.9,12,26.3],[ -2.0,20,24.8],[ -1.6,24,22.6],[ -1.5,26.5,22.4]],     // ch3 middle
  [[  0.3,-32,25.7],[  0.3,-29,26.5],[  2.7,-18,26.9],[  4.0,-12,26.6],[  6.5,0,25.9],[  9.3,12,24.3],[ 11.4,22,20.8],[ 11.6,26.5,19.8]],     // ch4 index
  [[  7.2,-32,24.5],[  7.2,-29,25.3],[  7.3,-18,26.0],[  7.4,-12,25.8],[  8.0,-8,25.5],[  8.8,-5,25.3]]                                        // ch5 wrist stub
];

/* ---- geometry helpers --------------------------------------------- */
function unit_vec(v) = v/norm(v);
CX = 0.5*(AP[2][0].x + AP[2][len(AP[2])-1].x);                 // arch centre x (SPAN_GAIN pivot)
// Apply SPAN_GAIN (widen/narrow about CX) and APEX_GAIN (scale height) to a 2D pt.
function shaped(p) = [ CX + (p.x-CX)*SPAN_GAIN, p.y*APEX_GAIN ];

// Inner cavity wall = outer arch pushed inward by WALL (skip the 2 feet so the
// bottom stays open). For each interior vertex: estimate the local tangent from
// its neighbours, take the perpendicular, flip it to point OUTWARD (away from the
// arch centre [CX, base_z]), then move the vertex inward by WALL along that normal.
function inner_arch(arch) = let(
    base_z = min([for(p=arch) shaped(p).y]) )
  [ for(i=[1:len(arch)-2])
      let( prev    = shaped(arch[max(i-1,1)]),
           next    = shaped(arch[min(i+1,len(arch)-2)]),
           tangent = unit_vec(next-prev),
           normal  = [tangent.y, -tangent.x],
           vtx     = shaped(arch[i]),
           out_normal = (normal*(vtx-[CX,base_z]) >= 0) ? normal : -normal )
      vtx - WALL*out_normal ];

// Outer arch of station i lifted into 3D: (X, AY[i], Z).
function out3d(i) = [ for(p=AP[i]) let(sp=shaped(p)) [sp.x, AY[i], sp.y] ];
// Inner arch of station i in 3D, closed below z=-10 (the 2 trailing points) so the
// cavity-subtraction solid is capped well under the plate -> clean open bottom.
function in3d(i)  = let( inner = inner_arch(AP[i]) )
    concat( [for(p=inner) [p.x, AY[i], p.y]],
            [ [inner[len(inner)-1].x, AY[i], -10], [inner[0].x, AY[i], -10] ] );

module dorsal_shell() {
    difference() {
        skin([for(i=[0:len(AY)-1]) out3d(i)], slices=0, caps=true);   // solid arch dome
        skin([for(i=[0:len(AY)-1]) in3d(i)],  slices=0, caps=true);   // hollow it (open bottom)
        for (channel = CH) path_sweep(circle(r=CH_R), channel);       // cable channels
    }
}

// =============================================================================
// PART 2 — THUMB PIVOT MOUNT (+X)                              [show_thumb]
// -----------------------------------------------------------------------------
// Built from readable PRIMITIVES (dialed interactively in templates/
// thumb_build.scad against the ghost). IoU 0.74.
// thumb_mount() = union(2 side prongs + deck + back wall + base + fin + cap)
//                 minus the 2 cable channels. Editable: change a number per piece.
// Needs BOSL2 (cuboid / edge constants) — included at the top of this file.
// =============================================================================

// ---- helper primitives ------------------------------------------------------
// box with top+bottom horizontal edges rounded (vertical edges sharp)
module rbox(w, l, h, rnd) {
    r = min(rnd, w/2 - 0.05, l/2 - 0.05, h/2 - 0.05);
    if (rnd > 0) cuboid([w, l, h], rounding = r, edges = ["X", "Y"]);
    else cube([w, l, h], center = true);
}
// box with only the chosen top/bottom edges rounded (tf/tb/bf/bb along Y; tl/tr/bl/br along X)
module rbox_edges(w, l, h, rnd, tf, tb, bf, bb, tl, tr, bl, br) {
    ylim = (tf||tb||bf||bb) ? min(w, h)/2 : 1e9;
    xlim = (tl||tr||bl||br) ? min(l, h)/2 : 1e9;
    r = min(rnd, ylim - 0.05, xlim - 0.05);
    es = [ if (tf) TOP+LEFT, if (tb) TOP+RIGHT, if (bf) BOT+LEFT, if (bb) BOT+RIGHT,
           if (tl) TOP+FWD,  if (tr) TOP+BACK,  if (bl) BOT+FWD,  if (br) BOT+BACK ];
    if (rnd > 0 && len(es) > 0) cuboid([w, l, h], rounding = r, edges = es);
    else cube([w, l, h], center = true);
}
// all-edges-rounded box (the fin cap)
module rcap(w, l, h, rnd) {
    r = min(rnd, w/2 - 0.05, l/2 - 0.05, h/2 - 0.05);
    if (r > 0) cuboid([w, l, h], rounding = r);
    else cube([w, l, h], center = true);
}
// placement wrappers: position (x,y,z), rotate (tilt about Y, yaw about Z), grow-anchor (ax,ay,az)
module gbox(x, y, z, w, l, h, rot, tilt, ax, ay, az, rnd)
    translate([x, y, z]) rotate([0, tilt, rot]) translate([ax*w/2, ay*l/2, az*h/2]) rbox(w, l, h, rnd);
module gbox3(x, y, z, w, l, h, rot, tilt, ax, ay, az, rnd, tf, tb, bf, bb, tl, tr, bl, br)
    translate([x, y, z]) rotate([0, tilt, rot]) translate([ax*w/2, ay*l/2, az*h/2]) rbox_edges(w, l, h, rnd, tf, tb, bf, bb, tl, tr, bl, br);
module gcyl(x, y, z, r, len, rot, tilt, az)
    translate([x, y, z]) rotate([0, tilt, rot]) translate([0, 0, az*len/2]) cylinder(r = r, h = len, center = true, $fn = 48);

// keyhole pin bore: round through prong A, rect slot through prong B (measured)
thumb_bore_c = [28.7, -9.6, 5.8];  thumb_bore_ang = 50.3;   // axis 50.3deg in XY at z5.8
module thumb_bore() {
    translate(thumb_bore_c) rotate([0, 0, thumb_bore_ang]) {
        translate([-1, 0, 0]) rotate([0,90,0]) cylinder(h = 8, r = 2.6, center = true, $fn = 64); // round bore
        translate([11, 0, 0]) cube([8, 3.9, 5.9], center = true);                                  // rect slot
    }
}
// top tool: the dorsal crown is a 2-way curved dome (ghost top rises to z20.5 at the inner
// x23 junction, ~19 over the prongs, ~18 at the +X tip) — a flat cut sheared the crown and
// left the prongs proud. Clip the thumb top to the TRUE ghost dome (the box only bounds it).
module thumb_top_round()
    intersection() {
        translate([24, -4, 11]) cube([60, 64, 46], center = true);   // thumb-region safety bound
        import(ghost_stl);                                           // top follows the real ghost dome
    }

// body fill + shell-wall junction — measured boxes CLIPPED to the ghost (conforms to
// the original surface; keeps the bore/channels open).
module thumb_fill()           intersection() { translate([30, -4, 10.5]) cube([16, 28, 21], center = true); import(ghost_stl); }
module thumb_shell_junction() intersection() { translate([18, -4, 10.5]) cube([ 8, 28, 21], center = true); import(ghost_stl); }

// ---- the thumb mount --------------------------------------------------------
module thumb_mount() {
  intersection() {
    difference() {
        union() {
            // two clevis side prongs (rounded -Y ends)
            gbox3(27.3, -9.0, 0,  5.2, 19, 20,  50, 0,  0,0,1, 7, false,false,false,false, true,false,true,false); // prong A
            gbox3(33.5,  0.0, 0,  5.0, 17, 20,  50, 0,  0,0,1, 7, false,false,false,false, true,false,true,false); // prong B
            gbox (28.5, -7.5, 18, 10,  8,  1, -40, 50, 1,1,1, 0);   // top deck (bridges the prongs)
            gbox (24.0,  6.0, 0,  2,  10, 19,  90, 0,  0,0,1, 0);   // back wall (+Y)
            gbox (18.0, -4.0, 0,  15,  9,  2,  50, 0,  1,0,1, 0);   // base plate (-> palm)
            // fin blade + cap on top
            gbox (34.0, -7.5, 12.5, 5, 2.5, 3.1, -40, 45, 0,0,1, 0);                                  // fin
            translate([34.0,-7.5,12.5]) rotate([0,45,-40]) translate([0,0,3.1 + 1.2/2])
                rcap(5 + 0.4, 2.5 + 0.4, 1.2, 0.2);                                                    // fin cap
            thumb_fill();             // body mass (ghost-clipped)
            thumb_shell_junction();   // fuse into the dome +X wall (ghost-clipped)
        }
        gcyl(22.5, 2.0, 0,  1, 23,    0,  0, 1);   // cable channel 1
        gcyl(25.0, 0.0, 6,  1, 15.5, 140, 25, 0);  // cable channel 2
        thumb_bore();                              // keyhole pin bore (round + rect)
    }
    thumb_top_round();                             // round the dorsal top into a dome
  }
}

// ---- coloured view (each part a distinct colour, for identification) --------
module thumb_colored() {
    color("Red")      gbox3(27.3, -9.0, 0,  5.2, 19, 20,  50, 0, 0,0,1, 7, false,false,false,false, true,false,true,false); // prong A
    color("Blue")     gbox3(33.5,  0.0, 0,  5.0, 17, 20,  50, 0, 0,0,1, 7, false,false,false,false, true,false,true,false); // prong B
    color("Orange")   gbox (28.5, -7.5, 18, 10,  8,  1, -40, 50, 1,1,1, 0);   // deck
    color("Purple")   gbox (24.0,  6.0, 0,  2,  10, 19,  90, 0,  0,0,1, 0);    // back wall
    color("Green")    gbox (18.0, -4.0, 0,  15,  9,  2,  50, 0,  1,0,1, 0);    // base plate
    color("Indigo")   gbox (34.0, -7.5, 12.5, 5, 2.5, 3.1, -40, 45, 0,0,1, 0); // fin
    color("DeepPink") translate([34.0,-7.5,12.5]) rotate([0,45,-40]) translate([0,0,3.1 + 1.2/2]) rcap(5.4, 2.9, 1.2, 0.2); // fin cap
    color("Cyan")     gcyl(22.5, 2.0, 0,  1, 23,    0,  0, 1);   // channel 1 (subtracted)
    color("Magenta")  gcyl(25.0, 0.0, 6,  1, 15.5, 140, 25, 0);  // channel 2 (subtracted)
}

// =============================================================================
// PART 3 — FINGER PIVOT CLEVISES (knuckles, +Y)                [show_knuckles]
// -----------------------------------------------------------------------------
// Each measured individually (IoU 0.90-0.94), rebuilt as ROUND eye lobes.
// Each prong BODY is a CYLINDER about the pin axis X (a true round pivot eye /
// boss), measured radius EYE_R~6 (radial occupancy of orig_aligned.stl: the eye
// lobe front/down reach 5.9mm), centred on the bore (cy, z6), spanning the
// prong's measured X-band, HULLED to a small floor footprint so the neck tapers
// (rounded) to the plate. A rear-only palm-merge BACKBOX (entirely behind the
// eye centre, -Y) fills the neck that welds into the palm body for volume/IoU;
// because it stops AT the eye centre it never touches the +Y front, so the front
// silhouette stays the round lobe. Everything clip_ghost-trimmed to the true
// envelope. KEYHOLE pin passage kept EXACT: round bore r2.5 (z6) / rect slot 4x6.
//   pinky : slot[-35.5,-31.8] | bore[-25.7,-18.0]  (eye cy30 z6)
//   ring  : slot[-21.5,-17.8] | bore[-11.7, -5.2]  (eye cy36 z6)
//   middle: bore[-11.5,-3.8]  | shared bore[2.5,10.3] (eye cy40 z6)
//   index : shared bore[2.5,10.3] | slot[16.5,19.8]   (eye cy40 z6)
// =============================================================================
// --- KEYHOLE pin-passage dimensions (kept EXACT; functional mating interface) ---
// Each clevis passes the pin through one prong as a round BORE (r=BR) and the
// other as a rect SLOT (SW x SH) so the finger tab can drop in and rotate.
BR = 2.5;     // round pin bore radius (find_holes: r2.50, 100% circularity)
SW = 4.0;     // rect slot width  (Y)
SH = 6.0;     // rect slot height (Z)
CZ = 6.0;     // eye / bore centre Z
// MEASURED disc geometry (ray-cast about (cy, z6) on orig_aligned.stl):
//   exposed face front+bottom (angles 270deg->0->90) = clean circle R_FOOT=5.9 -> disc BOTTOM at
//     z = 6 - 5.9 = 0.1 == TANGENT to the plate (smooth round-to-floor, no chord, no foot).
//   top/back (angles 90->240) grows to ~7.2..8.9 where the disc merges into the spine + palm body.
// The old single cylinder used r=7.6 centred at z6 -> the disc BOTTOM was at z=-1.6, i.e. it plunged
// 1.6mm THROUGH the plate and got sliced into a wide flat chord with a hard right-angle dihedral =
// the square FOOT. Fix: hull a FOOT disc (R_FOOT, tangent) with a raised TOP-fill disc (R_TOP) so the
// model's OWN bottom is the tangent circle (round to the floor) yet the top/back still overfills for
// clip to carve the exact ghost. No reliance on clip to hide a sub-floor plunge.
R_FOOT = 5.9;   // exposed disc radius -> bottom tangent to plate at z0.1
R_TOP  = 7.6;   // raised top-fill disc radius (overfills top/back; clip_ghost trims to envelope)
Z_TOP  = 8.6;   // centre Z of the top-fill disc (its bottom z=1.0, never below the plate)
NECK_B = 14;  // palm-merge backbox reach back toward palm (-Y from cy)
NECK_Z = 20;  // palm-merge backbox height (above ghost dorsal ~17.4 so clip carves the rounded top)

module bore(x0,x1,cy) translate([x0-1,cy,CZ]) rotate([0,90,0]) cylinder(h=x1-x0+2,r=BR);
module slot(x0,x1,cy) translate([x0-1,cy-SW/2,CZ-SH/2]) cube([x1-x0+2,SW,SH]);
module spine(sx0,sx1,cy) {
    translate([sx0-0.4,cy-5.2,13.0]) cube([sx1-sx0+0.8,4.2,2.6]);  // back top rim
    translate([sx0-0.4,cy-10.0, 0.0]) cube([sx1-sx0+0.8,3.2,2.4]); // back floor
}
// ROUND eye lobe: cylinder boss about the pin axis (R=EYE_R), tangent to the plate so the
// disc rounds SMOOTHLY into the floor (no plunge -> no flat chord, no square foot). A thin
// ROUNDED coaxial floor bead set BEHIND the disc front (toward the palm, -Y) is hulled in to
// taper the neck down to the plate; because the bead stays behind cy the +Y silhouette is the
// pure round disc. No flat rect root -> the model's OWN shape is round to the floor.
module eye_lobe(x0,x1,cy) hull() {
    translate([x0,cy,CZ])    rotate([0,90,0]) cylinder(h=x1-x0, r=R_FOOT, $fn=96); // FOOT disc: tangent to plate
    translate([x0,cy,Z_TOP]) rotate([0,90,0]) cylinder(h=x1-x0, r=R_TOP,  $fn=96); // TOP-fill disc (raised, never sub-floor)
    translate([x0, cy-NECK_B, 0.0]) cube([x1-x0, NECK_B, 0.6]); // solid flat rear floor root (behind disc front; no foot)
}
// rear-only palm-merge fill: behind the eye centre (-Y), width spans the finger so
// adjacent fingers' boxes overlap and weld; clip_ghost makes it the exact ghost neck.
module backbox(xc, cy) translate([xc-9, cy-NECK_B, 0]) cube([18, NECK_B, NECK_Z]);

// clip children to the ORIGINAL envelope: trims lobe/neck/backbox overflow to the
// true ghost surface; the keyhole bore + finger-tab slot are voids in the ghost so
// the clip leaves them open; each link still difference()s its bore/slot afterwards.
module clip_ghost() intersection() { children(); import(ghost_stl, convexity=8); }

// --- the four clevises --------------------------------------------------------
// Each: build the two eye lobes + spine + palm-merge backbox, clip the lot to the
// ghost envelope, then cut the keyhole (slot through one prong, bore through other).
module link_pinky_ring() {
    difference() {
        clip_ghost() union() {
            eye_lobe(-35.5,-31.8,30); eye_lobe(-25.7,-18.0,30);
            spine(-31.8,-25.7,30);    backbox(-28.8,30);
        }
        slot(-35.5,-31.8,30); bore(-25.7,-18.0,30);
    }
}
module link_ring_ring() {
    difference() {
        clip_ghost() union() {
            eye_lobe(-21.5,-17.8,36); eye_lobe(-11.7,-5.2,36);
            spine(-17.8,-11.7,36);    backbox(-14.8,36);
        }
        slot(-21.5,-17.8,36); bore(-11.7,-5.2,36);
    }
}
module link_middle_ring() {
    difference() {
        clip_ghost() union() {
            eye_lobe(-11.5,-3.8,40); eye_lobe(2.5,10.3,40);
            spine(-3.8,2.5,40);      backbox(-0.7,40);
        }
        bore(-11.5,-3.8,40); bore(2.5,10.3,40);
    }
}
module link_index_ring() {
    difference() {
        clip_ghost() union() {
            eye_lobe(2.5,10.3,40); eye_lobe(16.5,19.8,40);
            spine(10.3,16.5,40);   backbox(13.3,40);
        }
        bore(2.5,10.3,40); slot(16.5,19.8,40);
    }
}
module finger_rings() { link_pinky_ring(); link_ring_ring(); link_middle_ring(); link_index_ring(); }

// dome<->clevis junction merged with the clevises in ONE ghost-clip (manifold):
// raw lobes/spines/backboxes + a front junction band, clipped once, then bores/
// slots/cable-channels subtracted. Closes the gap between the dome and the clevises.
module front_assembly() {
  difference() {
    intersection() {
      union() {
        eye_lobe(-35.5,-31.8,30); eye_lobe(-25.7,-18.0,30); spine(-31.8,-25.7,30); backbox(-28.8,30);
        eye_lobe(-21.5,-17.8,36); eye_lobe(-11.7, -5.2,36); spine(-17.8,-11.7,36); backbox(-14.8,36);
        eye_lobe(-11.5, -3.8,40); eye_lobe(  2.5, 10.3,40); spine( -3.8,  2.5,40); backbox(-0.7,40);
        eye_lobe(  2.5, 10.3,40); eye_lobe( 16.5, 19.8,40); spine( 10.3, 16.5,40); backbox(13.3,40);
        translate([-37,22,10]) cube([57,20,14]);   // dome->clevis junction band
      }
      import(ghost_stl, convexity=8);
    }
    slot(-35.5,-31.8,30); bore(-25.7,-18.0,30);
    slot(-21.5,-17.8,36); bore(-11.7,-5.2,36);
    bore(-11.5,-3.8,40);  bore( 2.5,10.3,40);
    bore( 2.5,10.3,40);   slot(16.5,19.8,40);
    for (channel = CH) path_sweep(circle(r=CH_R), channel);   // keep cable channels open
  }
}

// =============================================================================
// PART 4 — DORSAL FINGER FINS (blade) + FIN CAPS (rounded crown)  [show_fins]
// -----------------------------------------------------------------------------
// Measured from the ghost: ring/middle/index each have a back-swept blade with an
// integral rounded crown (the crown is the blade's narrowed teardrop top, split
// into finger_fin_caps() — NOT a wider thumb-style overhang). PINKY has no fin.
// =============================================================================

// [ name, xc, yf(front face Y), base_z, shoulder_z, peak_z, depth(Y), thk(X) ]
finger_fins_tbl = [
    [ "pinky",  -28.75, 24.40, 13.0, 16.00, 18.35, 5.50, 2.85 ],  // smaller, shifted back/down
    [ "ring",   -14.80, 30.32, 13.0, 16.23, 18.51, 5.68, 2.85 ],
    [ "middle",  -0.80, 34.32, 13.0, 16.23, 18.51, 5.68, 2.85 ],
    [ "index",   13.20, 34.32, 13.0, 16.23, 18.51, 5.68, 2.85 ],
];
fin_round   = 0.7;   // 2D edge rounding (vertical edges + crown)
fin_peak_dy = 0.38;  // crown apex offset in +Y from the front face
cap_overlap = 0.8;   // crown roots this far down into the blade (clean seam)

// A Y-Z polygon profile, extruded `thk` along X (the blade is thin in X). The
// offset(r)/offset(-r) pair rounds the 2D outline's corners by fin_round before
// extruding (grow-then-shrink leaves rounded convex corners, sharp footprint).
module _fin_extrude(xc, yf, base_z, thk, pts)
    translate([xc, yf, base_z]) rotate([90, 0, 90]) translate([0, 0, -thk/2])
        linear_extrude(height = thk) offset(r = fin_round) offset(delta = -fin_round) polygon(pts);

// Lower blade: a rectangle from the base up to the shoulder (heights are local,
// measured up from base_z).
module fin_blade(xc, yf, base_z, shoulder_z, depth, thk) {
    shoulder_h = shoulder_z - base_z;
    _fin_extrude(xc, yf, base_z, thk, [[0,0], [depth,0], [depth,shoulder_h], [0,shoulder_h]]);
}
module finger_fins() { for (f = finger_fins_tbl) fin_blade(f[1],f[2],f[3],f[4],f[6],f[7]); }

// Crown cap: the teardrop top of the blade. Roots cap_overlap below the shoulder
// (clean seam into the blade) and tapers to a peak pulled fin_peak_dy in +Y.
module fin_cap(xc, yf, base_z, shoulder_z, peak_z, depth, thk) {
    root_h = shoulder_z - base_z - cap_overlap;
    peak_h = peak_z - base_z;
    _fin_extrude(xc, yf, base_z, thk,
        [[0,root_h], [depth,root_h], [depth, shoulder_z-base_z], [fin_peak_dy, peak_h]]);
}
module finger_fin_caps() { for (f = finger_fins_tbl) fin_cap(f[1],f[2],f[3],f[4],f[5],f[6],f[7]); }

// =============================================================================
// PART 5 — WRIST HINGE EARS (-Y) + SIDE WALLS (gauntlet)        [show_wrist]
// -----------------------------------------------------------------------------
// The hinge ears + the thin side walls that tie the ears to the floor and palm
// body.
// =============================================================================
EAR_BORE_R = 3.00;   // hinge pin through-bore radius
EAR_CB_R   = 3.88;   // inner counterbore radius (pin head recess)
EAR_CB_D   = 0.90;   // inner counterbore depth
EAR_R      = 7.75;   // ear disc radius
EAR_W      = 5.00;   // ear disc thickness (along X, the pin axis)
EAR_Y      = -38.0;  // ear / hinge centre Y
EAR_Z      = 8.0;    // ear / hinge centre Z
// Ear stations: [centre X, inner-face sign]. Shared by wrist() AND wrist_back()
// (which re-cuts the same bores through its ghost-clip) — keep them in lockstep.
EARS       = [[20.5, -1], [-36.0, +1]];

// One wrist ear: a disc on the X pin-axis, minus the through-bore, minus an inner
// counterbore. inner_sign = which side (+1 / -1) the disc's inner face is toward.
module wrist_ear(cx, inner_sign) {
    inner_face = cx + inner_sign * EAR_W/2;
    difference() {
        translate([cx, EAR_Y, EAR_Z]) rotate([0,90,0]) cylinder(h = EAR_W, r = EAR_R, center = true);
        translate([cx, EAR_Y, EAR_Z]) rotate([0,90,0]) cylinder(h = EAR_W + 2, r = EAR_BORE_R, center = true);
        translate([inner_face - inner_sign*EAR_CB_D/2, EAR_Y, EAR_Z])
            rotate([0,90,0]) cylinder(h = EAR_CB_D, r = EAR_CB_R, center = true);
    }
}
// Side-wall cross-section in the Y-Z plane (measured), rising from the floor up
// toward the dome rim; linear-extruded along X to make a thin gauntlet wall.
WALL_PROFILE = [ [-44,3.1],[-44,13.1],[-42,14.6],[-40,15.6],[-38,16.6],[-36,17.1],[-34,18.1],
                 [-32,19.1],[-30,20.1],[-28,21.0],[-26,21.0],[-26,0.0],[-38,0.0],[-40,0.6],[-42,1.1] ];
// Extrude WALL_PROFILE (drawn in Y-Z) as a wall `thick` deep along X at X=x0.
// The multmatrix is just an axis swap: profile X->world Z, profile Y->world X,
// extrusion height->world Y, so the Y-Z polygon stands up correctly in 3D.
module yz_wall(x0, thick) {
    translate([x0,0,0]) multmatrix([[0,0,1,0],[1,0,0,0],[0,1,0,0],[0,0,0,1]]) linear_extrude(thick) polygon(WALL_PROFILE);
}
// Left + right gauntlet side walls, each pierced by a hinge window on the pin axis.
// wall = [x0, thick].
module wrist_walls() {
    for (wall = [[-38.5,4.5],[18.5,4.0]]) difference() {
        yz_wall(wall[0], wall[1]);
        translate([wall[0]-1, -38, 8]) rotate([0,90,0]) cylinder(h = wall[1]+2, r = 2.5);   // hinge window
    }
}
module wrist() { for (e = EARS) wrist_ear(e[0], e[1]); wrist_walls(); }

// =============================================================================
// PART 6 — WRIST BACK WALL (-Y gauntlet cuff)                  [show_wrist_back]
// -----------------------------------------------------------------------------
//  Fills the back band between the dome rim and the wrist ears so the
//  dome -> side-walls -> ears read as ONE continuous gauntlet back wall,
//  matching the ghost (which the thin parametric wrist_walls under-filled).
//
//  Method: GHOST-CLIP (the project's accepted idiom, as used by
//  front_assembly / thumb_fill / the floor front): intersect a solid block
//  spanning the back band with import(ghost_stl) -> the EXACT ghost envelope
//  (continuous wall, correct thickness, lug bosses, floor) in that band.
//  Then re-cut the functional voids so they stay OPEN:
//    - the 2 hinge pin bores + inner counterbores (re-cut as clean tunnels)
//    - the 2 hinge windows (covered by the r3 tunnels, same axis)
//    - the cable-channel exits (re-subtract the dome CH sweeps)
//  Union this with the existing wrist()/dorsal_shell(); overlap is welded.
// =============================================================================

// Back-band clip box (measured from ghost occupancy, y -45..-24 / z 0..~21):
//   WB_Y1 sits just behind the dome rim station AY[0]=-30.5 so the fill
//   overlaps the dome legs (continuous, no seam); WB_Z1 stays below the
//   dome roof so the roof/channel mouths are owned by dorsal_shell.
WB_Y0 = -46.5;
WB_Y1 = -27.0;
WB_Z1 = 21.0;

module wrist_back() {
    difference() {
        intersection() {
            import(ghost_stl, convexity = 8);
            translate([-45, WB_Y0, 0]) cube([90, WB_Y1 - WB_Y0, WB_Z1]);
        }
        // --- keep the 2 hinge bores + counterbores + windows OPEN ---
        // one clean r=EAR_BORE_R tunnel per ear along X (EAR_Y,EAR_Z) clears the
        // lug bore AND the wall hinge window (same axis). The tunnel is wider
        // than the r2.5 wall window, but the union with the parametric wall
        // (solid in the r2.5..r3 annulus) restores the measured r2.5 window.
        for (ear = EARS) {
            cx = ear[0]; inner_sign = ear[1];
            translate([cx, EAR_Y, EAR_Z]) rotate([0,90,0])
                cylinder(h = 40, r = EAR_BORE_R, center = true);                  // through bore
            inner_face = cx + inner_sign*EAR_W/2;
            translate([inner_face - inner_sign*EAR_CB_D/2, EAR_Y, EAR_Z]) rotate([0,90,0])
                cylinder(h = EAR_CB_D, r = EAR_CB_R, center = true);              // inner counterbore
        }
        // --- keep the cable-channel exits OPEN ---
        for (channel = CH) path_sweep(circle(r = CH_R), channel);
    }
}

// =============================================================================
// PART 7 — PERFORATED PALMAR FLOOR + basket-weave vent grid (z 0..2) [show_grid]
// =============================================================================
plate_h = 2.0;        // floor plate thickness (z 0..2)
hole_long = 3.21;     // long side of a vent slot
hole_short = 2.13;    // short side of a vent slot
vent_pitch = 4.9;     // centre-to-centre spacing of the vent grid (both axes)
vent_x0 = 0.6;        // vent grid origin X
vent_y0 = -0.9;       // vent grid origin Y
vent_col0 = -6;       // vent column index range (X)
vent_col1 = 3;
vent_row0 = -5;       // vent row index range (Y)
vent_row1 = 4;
floor_outline = [ [24.4,-9.9],[22.8,-41.9],[17.8,-41.9],[17.8,-30.0],[-33.3,-30.0],[-33.3,-41.9],[-38.3,-41.9],[-40.4,3.6],[-37.4,21.9],[-35.5,26.8],[-35.5,33.3],[-31.7,33.3],[-31.7,23.6],[-25.7,23.6],[-25.7,33.3],[-21.7,33.3],[-21.7,39.3],[-17.7,39.3],[-17.7,29.6],[-11.7,29.6],[-11.7,39.3],[-7.7,39.3],[-7.7,36.7],[-5.7,36.7],[-5.7,40.5],[-7.7,40.5],[-7.7,43.3],[-3.7,43.3],[-3.7,33.6],[2.3,33.6],[2.6,43.3],[10.3,43.3],[10.3,33.6],[16.3,33.6],[16.3,43.3],[19.3,43.3],[23.6,21.3],[24.5,7.4],[30.0,6.2],[39.4,-1.6],[36.2,-5.4],[28.2,1.3],[24.3,-3.3],[32.3,-10.0],[29.1,-13.8] ];
FLOOR_CONFORM_Y = 22;   // +Y of this -> clip the floor FRONT to the ghost (conform under the connections)
module palm_floor_grid() {
    // The +Y front plate overhangs the ghost's hollow front underside under the finger
    // connections -> a protruding LEDGE the round discs sit on with a hard 90deg. Ghost-clip
    // ONLY the front band (Y>=FLOOR_CONFORM_Y): deletes the overhang where the ghost is hollow
    // (pinky/ring) and rounds the front edge down to the disc (middle/index). The back/thumb/
    // wrist floor stays the clean parametric plate (no clip -> no tangency slivers).
    intersection() {
        difference() {   // raw perforated flat plate (z 0..2)
            // offset(delta=0.2) grows the outline 0.2mm so the floor overlaps the
            // walls/ears it meets — turns coincident faces into a small overlap, so
            // the union stays watertight/manifold (no zero-thickness shared face).
            linear_extrude(plate_h) offset(delta = 0.2) polygon(floor_outline);
            // basket-weave vents: rectangles alternating orientation row-to-row
            for (col = [vent_col0:vent_col1]) for (row = [vent_row0:vent_row1]) {
                hole_sz = (row % 2 == 0) ? [hole_long, hole_short] : [hole_short, hole_long];
                translate([vent_x0 + vent_pitch*col, vent_y0 + vent_pitch*row, -0.5])
                    linear_extrude(plate_h + 1) square(hole_sz, center = true);
            }
        }
        union() {   // front (Y>=22): conform to ghost ; back: keep raw
            import(ghost_stl, convexity = 8);
            translate([-100, -200, -10]) cube([200, 200 + FLOOR_CONFORM_Y, 100]);
        }
    }
}

// =============================================================================
// MODEL — enabled features fused (union); global bores are cut per part
// =============================================================================
module model() {
    if (show_shell)      dorsal_shell();
    if (show_knuckles)   front_assembly();  // 4 round clevises + dome<->clevis junction (one clip)
    if (show_fins)     { finger_fins(); finger_fin_caps(); }  // ring/middle/index blade + crown cap
    if (show_thumb)      thumb_mount();   // readable primitive lug + bores
    if (show_wrist)      wrist();         // hinge ears + gauntlet side walls
    if (show_wrist_back) wrist_back();    // gauntlet back band (ghost-clip)
    if (show_grid)       palm_floor_grid();
}
// coloured per-part view (debug_colors) — each feature a distinct colour
module model_colored() {
    if (show_shell)      color("SkyBlue")    dorsal_shell();
    if (show_knuckles)   color("Orange")     front_assembly();  // connections + dome junction
    if (show_fins)     { color("LimeGreen")  finger_fins(); color("SpringGreen") finger_fin_caps(); }
    if (show_thumb)      thumb_colored();    // thumb sub-parts each a colour (see PART 2)
    if (show_wrist)      color("Plum")         wrist();
    if (show_wrist_back) color("MediumPurple") wrist_back();
    if (show_grid)       color("Khaki")      palm_floor_grid();
}

// ---- output / verification harness -----------------------------------------
module section_cube() {
    b = 300;
    if      (section == "longitudinal") translate([section_at, -b/2, -b/2]) cube(b);
    else if (section == "transverse")   translate([-b/2, section_at, -b/2]) cube(b);
    else if (section == "horizontal")   translate([-b/2, -b/2, section_at]) cube(b);
}
module ghost() { if (show_ghost) color(ghost_color, ghost_alpha) children(); }
// Standalone render — suppressed when a driver (e.g. _assembly.scad) sets
// no_assembly=true before `include`-ing this file, so it can call model() itself.
if (is_undef(no_assembly) || !no_assembly) {
if (section == "off") {
    if (debug_colors) model_colored();
    else color([0.95, 0.85, 0.20]) model();
    ghost() import(ghost_stl);   // drawn LAST -> shows as a transparent overlay (not occluded)
} else {
    difference() {
        if (debug_colors) model_colored(); else color([0.95, 0.85, 0.20]) model();
        section_cube();
    }
    ghost() difference() { import(ghost_stl); section_cube(); }
}
}
