// ============================================
// Symmetric Dome Cap - Parametric Reconstruction
// Source: Reborn_wrist_pin_cap.stl
// Generated by scripts/reconstruct_symmetric_cap.py
// ============================================
$fn = 128;
eps = 0.01;

// ---- Measured parameters ----
total_h        = 3.7500;   // height
bore_r         = 2.6998;   // inner through-bore radius
inner_cham     = 0.4050;   // inner bore bottom chamfer depth (45°)
counterbore_r  = 4.7000;   // inner bowl / counterbore radius
counterbore_z  = 2.0000;   // counterbore floor Z
outer_r_bot    = 7.5557;   // outer radius at Z=0 (bottom of chamfer)
dome_top_r     = 5.2538;   // outer dome radius at very top

// Outer dome arc - circular arc fit to SVG outer-contour slices
// Center=(arc_rc, arc_zc), Radius=arc_R
arc_rc = 5.2538;
arc_zc = 0.7526;
arc_R  = 2.9936;
a_bot  = -14.5608;   // arc angle (deg) at chamfer start
a_top  = 90.0000;   // arc angle (deg) at dome top
n_arc  = 48.0;        // arc polygon segments

// ---- 2D profile in RZ plane ----
module cap_profile() {
    arc_points = [for (i = [0 : n_arc])
        let(a = a_top + i * (a_bot - a_top) / n_arc)
        [arc_rc + arc_R * cos(a), arc_zc + arc_R * sin(a)]
    ];
    polygon(concat(
        // Inner bore with bottom chamfer
        [[bore_r + inner_cham, 0]],
        [[bore_r, inner_cham]],
        // Bore wall to counterbore floor
        [[bore_r, counterbore_z]],
        [[counterbore_r, counterbore_z]],
        // Counterbore wall to top
        [[counterbore_r, total_h]],
        // Top face
        [[dome_top_r, total_h]],
        // Outer dome arc (top → bottom)
        arc_points,
        // Outer chamfer foot
        [[outer_r_bot, 0]]
    ));
}

// ---- Main assembly ----
rotate_extrude($fn = 128)
    cap_profile();
