#!/usr/bin/env python3
"""
reconstruct.py — Automated STL-to-parametric-OpenSCAD reconstruction tool.

Analyses one or more STL files, selects the appropriate encoding strategy
(CSG primitives for simple prismatic parts, polyhedron() for organic/filleted
geometry), generates a self-contained OpenSCAD module for each part, and
assembles them into a single parametric SCAD file.

Usage
-----
Single part:
    python3 tools/reconstruct.py palm.stl --module palm_body --param palm_breadth_mm=83

Multiple parts assembled together:
    python3 tools/reconstruct.py finger_4.stl finger_5.stl hinge_4.stl \\
        --modules proximal_phalanx distal_phalanx finger_hinge \\
        --assembly middle_finger \\
        --param middle_finger_length_mm=72 palm_breadth_mm=83 \\
        --output models/my_finger.scad

Validate an existing SCAD against its source STLs:
    python3 tools/reconstruct.py finger_4.stl --validate models/my_finger.scad --module proximal_phalanx

Strategy selection
------------------
The tool computes the oblique-face ratio (fraction of face normals that are not
axis-aligned to within --axis-tol degrees).  If the ratio exceeds --organic-threshold
(default 0.40), the part is classified as organic and encoded as polyhedron().
Otherwise the Z-level structure is analysed and a CSG skeleton is attempted.

For the Kinetic Hand RH60, all parts showed 0.77–0.97 oblique-face ratio, so
polyhedron() was selected universally.  Simpler bracket-style parts (< 0.30
oblique ratio) will trigger the CSG path.
"""

import argparse
import json
import sys
import os
import textwrap
from pathlib import Path

import numpy as np

try:
    import trimesh
except ImportError:
    sys.exit("trimesh is required: pip3 install trimesh")


# ── Constants ────────────────────────────────────────────────────────────────

AXIS_VECTORS = np.array([
    [1, 0, 0], [-1, 0, 0],
    [0, 1, 0], [0, -1, 0],
    [0, 0, 1], [0, 0, -1],
], dtype=float)

SCAD_HEADER = """\
// {output_name}
// Auto-generated by tools/reconstruct.py
// Source STL(s): {sources}
//
// Parametric constants are surfaced at the top of each section.
// Edit the values under [Anthropometric inputs] to resize the model.
//
// Assembly coordinate frame:
{frame_comment}
"""

SCAD_PARAM_BLOCK = """\
/* [Anthropometric inputs] */
{param_lines}

/* [Visibility] */
{vis_lines}

/* [Hidden] */
// Reference dimensions (match source STL geometry at scale 1.0)
{ref_lines}

// Derived scale factors
{scale_lines}
"""


# ── Mesh analysis ─────────────────────────────────────────────────────────────

def load_mesh(path: str) -> trimesh.Trimesh:
    mesh = trimesh.load(path, force='mesh')
    if not isinstance(mesh, trimesh.Trimesh):
        raise ValueError(f"Could not load a single mesh from {path}")
    return mesh


def oblique_ratio(mesh: trimesh.Trimesh, axis_tol_deg: float = 5.0) -> float:
    """Fraction of faces whose normals are NOT within axis_tol_deg of any axis."""
    normals = mesh.face_normals
    tol = np.cos(np.radians(90 - axis_tol_deg))
    dots = np.abs(normals @ AXIS_VECTORS.T)
    axis_aligned = np.any(dots >= tol, axis=1)
    return float(np.sum(~axis_aligned) / len(normals))


def triage(mesh: trimesh.Trimesh, path: str) -> dict:
    bb = mesh.bounds
    extents = mesh.extents
    euler = mesh.euler_number
    genus = int((2 - euler) // 2)
    watertight = mesh.is_watertight
    ratio = oblique_ratio(mesh)

    return {
        "file": path,
        "vertices": int(len(mesh.vertices)),
        "faces": int(len(mesh.faces)),
        "extents_mm": {"x": float(extents[0]), "y": float(extents[1]), "z": float(extents[2])},
        "bounds": {"x": [float(bb[0,0]), float(bb[1,0])],
                   "y": [float(bb[0,1]), float(bb[1,1])],
                   "z": [float(bb[0,2]), float(bb[1,2])]},
        "watertight": watertight,
        "euler": int(euler),
        "genus": genus,
        "oblique_ratio": ratio,
    }


def z_levels(mesh: trimesh.Trimesh, tol: float = 0.01) -> list:
    zs = np.round(mesh.vertices[:, 2] / tol) * tol
    return sorted(set(zs.tolist()))


def unique_z_count(mesh: trimesh.Trimesh) -> int:
    return len(z_levels(mesh))


# ── Strategy selection ────────────────────────────────────────────────────────

def select_strategy(info: dict, organic_threshold: float) -> str:
    """
    Returns 'polyhedron' or 'csg'.

    CSG is only attempted when:
      - oblique_ratio < organic_threshold (few curved/filleted surfaces)
      - unique Z levels < 30 (prismatic extrusion stack)

    In practice all tested prosthetic hand parts from CAD tools exceed the
    threshold; CSG is included for simpler custom components.
    """
    if info["oblique_ratio"] >= organic_threshold:
        return "polyhedron"
    return "csg"


# ── Polyhedron encoding ───────────────────────────────────────────────────────

def mesh_to_polyhedron_module(mesh: trimesh.Trimesh, module_name: str,
                               description: str = "") -> str:
    bb = mesh.bounds
    lines = []
    if description:
        lines.append(f"// {description}")
    lines.append(f"// Vertices: {len(mesh.vertices)}  "
                 f"Faces: {len(mesh.faces)}  "
                 f"Volume: {mesh.volume:.2f} mm³")
    lines.append(f"// Bounds: "
                 f"x=[{bb[0,0]:.3f},{bb[1,0]:.3f}] "
                 f"y=[{bb[0,1]:.3f},{bb[1,1]:.3f}] "
                 f"z=[{bb[0,2]:.3f},{bb[1,2]:.3f}]")
    lines.append(f"module {module_name}() {{")
    lines.append("  polyhedron(convexity=10,")
    lines.append("    points=[")
    for v in mesh.vertices:
        lines.append(f"      [{v[0]:.6f},{v[1]:.6f},{v[2]:.6f}],")
    lines.append("    ],")
    lines.append("    faces=[")
    for f in mesh.faces:
        lines.append(f"      [{f[0]},{f[1]},{f[2]}],")
    lines.append("    ]")
    lines.append("  );")
    lines.append("}")
    return "\n".join(lines)


# ── CSG skeleton (for prismatic parts) ───────────────────────────────────────

def csg_skeleton(mesh: trimesh.Trimesh, module_name: str) -> str:
    """
    Emit a CSG skeleton based on the bounding box, with TODO markers for the
    analyst to fill in. Used when oblique_ratio < threshold.

    A full CSG reconstruction requires human interpretation of cross-sections;
    this skeleton provides the bounding box, Z levels, and a comment-driven
    scaffold to guide that work.
    """
    try:
        import shapely
        from shapely.geometry import MultiPolygon
        has_shapely = True
    except ImportError:
        has_shapely = False

    bb = mesh.bounds
    extents = mesh.extents
    levels = z_levels(mesh)
    n_levels = len(levels)

    lines = [
        f"// CSG skeleton for {module_name}",
        f"// Bounding box: {extents[0]:.2f} x {extents[1]:.2f} x {extents[2]:.2f} mm",
        f"// Z levels ({n_levels}): {levels[:10]}{'...' if n_levels > 10 else ''}",
        f"// Oblique-face ratio: {oblique_ratio(mesh):.2f} — prismatic geometry detected",
        f"//",
        f"// TODO: Replace the bounding-box placeholder below with proper CSG.",
        f"// Use tools/stl_cross_section.py to inspect each Z layer,",
        f"// tools/stl_zlevel.py to list face areas, and",
        f"// tools/stl_normals.py to locate cylinders and holes.",
        f"",
        f"module {module_name}() {{",
        f"  // Placeholder: full bounding box",
        f"  // Replace with union() / difference() of identified primitives",
        f"  translate([{bb[0,0]:.3f}, {bb[0,1]:.3f}, {bb[0,2]:.3f}])",
        f"  cube([{extents[0]:.3f}, {extents[1]:.3f}, {extents[2]:.3f}]);",
        f"  // TODO: subtract holes (genus = {int((2 - mesh.euler_number)//2)} through-hole(s))",
        f"}}",
    ]
    return "\n".join(lines)


# ── Assembly generation ───────────────────────────────────────────────────────

def build_assembly_module(assembly_name: str, module_names: list,
                           vis_names: list, params: dict) -> str:
    """
    Generate an assembly module that places all parts and applies
    a basic parametric scale transform derived from the supplied params.
    """
    lines = [f"module {assembly_name}() {{"]

    # If a scale parameter is present, emit a scale() wrapper comment
    scale_params = [k for k in params if k.endswith("_mm")]
    if scale_params:
        lines.append(f"  // Scale is driven by: {', '.join(scale_params)}")
        lines.append(f"  // Adjust the scale factors in the [Hidden] section above.")

    for mod, vis in zip(module_names, vis_names):
        lines.append(f"  if ({vis}) {mod}();")

    lines.append("}")
    return "\n".join(lines)


def build_param_section(params: dict, module_names: list, vis_names: list,
                         infos: list) -> str:
    """Generate the parameter block at the top of the SCAD file."""
    param_lines = []
    for k, v in params.items():
        # Infer a sensible range
        if k.endswith("_mm"):
            lo, hi = int(v * 0.5), int(v * 1.5)
            param_lines.append(f"{k} = {v};  // [{lo}:{hi}]")
        else:
            param_lines.append(f"{k} = {v};")

    vis_lines = [f"show_{n} = true;" for n in vis_names]

    ref_lines = []
    for k, v in params.items():
        if k.endswith("_mm"):
            ref_lines.append(f"REF_{k.upper()} = {v};  // reference = {v} mm")

    scale_lines = ["// Add derived scale factors here, e.g.:"]
    if "palm_breadth_mm" in params:
        scale_lines.append("s_xy = palm_breadth_mm / REF_PALM_BREADTH_MM;")

    return SCAD_PARAM_BLOCK.format(
        param_lines="\n".join(param_lines),
        vis_lines="\n".join(vis_lines),
        ref_lines="\n".join(ref_lines),
        scale_lines="\n".join(scale_lines),
    )


# ── Validation ────────────────────────────────────────────────────────────────

def validate(source_path: str, scad_path: str, module_name: str,
             n_samples: int = 50_000) -> dict:
    """
    Extract the polyhedron() data from a SCAD module and compute Hausdorff
    distance against the source STL.  Requires the SCAD to use polyhedron()
    encoding (not CSG or import()).
    """
    # Parse vertices and faces from the SCAD file
    text = Path(scad_path).read_text()

    # Find the module
    mod_start = text.find(f"module {module_name}()")
    if mod_start == -1:
        return {"error": f"Module '{module_name}' not found in {scad_path}"}

    # Extract points and faces with simple regex
    import re
    points_block = re.search(r'points=\[(.*?)\]', text[mod_start:], re.DOTALL)
    faces_block  = re.search(r'faces=\[(.*?)\]',  text[mod_start:], re.DOTALL)
    if not points_block or not faces_block:
        return {"error": "Could not parse polyhedron() data — CSG modules require rendered STL for comparison"}

    pts = re.findall(r'\[([-\d.]+),([-\d.]+),([-\d.]+)\]', points_block.group(1))
    fcs = re.findall(r'\[(\d+),(\d+),(\d+)\]', faces_block.group(1))

    if not pts or not fcs:
        return {"error": "Empty points or faces in polyhedron()"}

    vertices = np.array([[float(x), float(y), float(z)] for x, y, z in pts])
    faces    = np.array([[int(a), int(b), int(c)] for a, b, c in fcs])

    reconstructed = trimesh.Trimesh(vertices=vertices, faces=faces, process=False)
    original      = load_mesh(source_path)

    # Sample points on both surfaces
    orig_pts, _  = trimesh.sample.sample_surface(original,      n_samples)
    recon_pts, _ = trimesh.sample.sample_surface(reconstructed, n_samples)

    _, d1, _ = trimesh.proximity.closest_point(reconstructed, orig_pts)
    _, d2, _ = trimesh.proximity.closest_point(original,      recon_pts)

    all_d = np.concatenate([d1, d2])
    hausdorff = float(np.max(all_d))
    mean_d    = float(np.mean(all_d))

    return {
        "source": source_path,
        "module": module_name,
        "hausdorff_mm": hausdorff,
        "mean_mm": mean_d,
        "p95_mm": float(np.percentile(all_d, 95)),
        "volume_original_mm3": float(original.volume) if original.is_watertight else None,
        "volume_reconstructed_mm3": float(reconstructed.volume) if reconstructed.is_watertight else None,
        "pass": hausdorff <= 0.1,
    }


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Reconstruct STL file(s) as parametric OpenSCAD source.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""\
            Examples
            --------
            # Single part — polyhedron encoding
            python3 tools/reconstruct.py models/kinetic_hand/finger_4.stl \\
                --module proximal_phalanx \\
                --param middle_finger_length_mm=72 palm_breadth_mm=83 \\
                --output models/finger_proximal.scad

            # Multiple parts with assembly
            python3 tools/reconstruct.py \\
                models/kinetic_hand/finger_4.stl \\
                models/kinetic_hand/finger_5.stl \\
                models/kinetic_hand/hinge_4.stl \\
                --modules proximal_phalanx distal_phalanx finger_hinge \\
                --assembly middle_finger \\
                --param middle_finger_length_mm=72 palm_breadth_mm=83 \\
                --output models/middle_finger.scad

            # Validate existing SCAD against source
            python3 tools/reconstruct.py models/kinetic_hand/finger_4.stl \\
                --validate models/kinetic_hand_finger_middle.scad \\
                --module proximal_phalanx
        """)
    )
    parser.add_argument("stl", nargs="+", help="STL file(s) to reconstruct")
    parser.add_argument("--module",  help="Module name for single-STL reconstruction")
    parser.add_argument("--modules", nargs="+", help="Module names (one per STL, multi-STL mode)")
    parser.add_argument("--assembly", help="Name for the top-level assembly module")
    parser.add_argument("--output", "-o", help="Output .scad file path")
    parser.add_argument("--param", nargs="*", metavar="KEY=VALUE",
                        help="Anthropometric parameters (e.g. palm_breadth_mm=83)")
    parser.add_argument("--organic-threshold", type=float, default=0.40,
                        help="Oblique-face ratio above which polyhedron() is used (default: 0.40)")
    parser.add_argument("--axis-tol", type=float, default=5.0,
                        help="Degrees from axis to count as axis-aligned (default: 5)")
    parser.add_argument("--validate", metavar="SCAD",
                        help="Validate an existing SCAD file against the source STL(s)")
    parser.add_argument("--triage-only", action="store_true",
                        help="Run mesh triage and print results without generating SCAD")
    parser.add_argument("--json", action="store_true", help="Output triage results as JSON")
    args = parser.parse_args()

    # ── Validation mode ──────────────────────────────────────────────────────
    if args.validate:
        results = []
        module_names = args.modules or ([args.module] * len(args.stl) if args.module else [])
        if not module_names:
            parser.error("--validate requires --module or --modules")
        for stl_path, mod in zip(args.stl, module_names):
            print(f"Validating {mod} against {stl_path} ...", file=sys.stderr)
            r = validate(stl_path, args.validate, mod)
            results.append(r)
            status = "PASS" if r.get("pass") else "FAIL"
            if "error" in r:
                print(f"  ERROR: {r['error']}")
            else:
                print(f"  Hausdorff: {r['hausdorff_mm']:.6f} mm  [{status}]")
                print(f"  Mean:      {r['mean_mm']:.6f} mm")
        if args.json:
            print(json.dumps(results, indent=2))
        return

    # ── Load meshes ──────────────────────────────────────────────────────────
    meshes = []
    infos  = []
    for path in args.stl:
        print(f"Loading {path} ...", file=sys.stderr)
        m = load_mesh(path)
        i = triage(m, path)
        i["unique_z_levels"] = unique_z_count(m)
        i["strategy"] = select_strategy(i, args.organic_threshold)
        infos.append(i)
        meshes.append(m)
        print(f"  {i['faces']} faces  oblique={i['oblique_ratio']:.2f}  "
              f"genus={i['genus']}  strategy={i['strategy']}", file=sys.stderr)

    if args.triage_only:
        if args.json:
            print(json.dumps(infos, indent=2))
        else:
            for i in infos:
                print(f"\n{i['file']}")
                print(f"  Vertices:     {i['vertices']}")
                print(f"  Faces:        {i['faces']}")
                print(f"  Extents (mm): {i['extents_mm']}")
                print(f"  Watertight:   {i['watertight']}")
                print(f"  Genus:        {i['genus']}")
                print(f"  Oblique ratio:{i['oblique_ratio']:.3f}")
                print(f"  Unique Z lvls:{i['unique_z_levels']}")
                print(f"  → Strategy:   {i['strategy']}")
        return

    # ── Resolve module names ─────────────────────────────────────────────────
    if len(meshes) == 1:
        module_names = [args.module or Path(args.stl[0]).stem]
    else:
        if args.modules and len(args.modules) == len(meshes):
            module_names = args.modules
        else:
            module_names = [Path(p).stem for p in args.stl]
            if args.modules:
                print("Warning: --modules count doesn't match STL count; "
                      "using filenames as module names.", file=sys.stderr)

    vis_names = [f"show_{n}" for n in module_names]

    # ── Parse parameters ─────────────────────────────────────────────────────
    params = {}
    for kv in (args.param or []):
        if "=" not in kv:
            parser.error(f"--param values must be KEY=VALUE, got: {kv}")
        k, v = kv.split("=", 1)
        try:
            params[k] = float(v) if "." in v else int(v)
        except ValueError:
            params[k] = v

    # ── Generate SCAD ────────────────────────────────────────────────────────
    output_name = args.output or (module_names[0] + ".scad")
    sources = ", ".join(os.path.basename(p) for p in args.stl)

    # Coordinate frame comment (inferred from Z bounds)
    all_z_min = min(m.bounds[0, 2] for m in meshes)
    all_z_max = max(m.bounds[1, 2] for m in meshes)
    frame_comment = (f"//   Z = {all_z_min:.1f} mm → part base\n"
                     f"//   Z = {all_z_max:.1f} mm → part top")

    sections = [
        SCAD_HEADER.format(
            output_name=os.path.basename(output_name),
            sources=sources,
            frame_comment=frame_comment,
        ),
        build_param_section(params, module_names, vis_names, infos),
    ]

    for mesh, info, mod_name, stl_path in zip(meshes, infos, module_names, args.stl):
        strategy = info["strategy"]
        desc = f"{os.path.basename(stl_path)} — {strategy} encoding"
        if strategy == "polyhedron":
            sections.append(mesh_to_polyhedron_module(mesh, mod_name, desc))
        else:
            print(f"  Note: {mod_name} uses CSG skeleton — manual completion required.",
                  file=sys.stderr)
            sections.append(csg_skeleton(mesh, mod_name))

    if args.assembly and len(module_names) > 1:
        sections.append(
            build_assembly_module(args.assembly, module_names, vis_names, params)
        )
        sections.append(f"\n// Render\n{args.assembly}();")
    elif module_names:
        sections.append(f"\n// Render\n{module_names[0]}();")

    scad_text = "\n\n".join(sections)

    if args.output:
        Path(args.output).write_text(scad_text)
        print(f"\nWritten: {args.output} ({len(scad_text):,} bytes)", file=sys.stderr)
    else:
        print(scad_text)

    # ── Auto-validate polyhedron outputs ────────────────────────────────────
    if args.output and any(i["strategy"] == "polyhedron" for i in infos):
        print("\nValidating output ...", file=sys.stderr)
        all_pass = True
        for stl_path, mod, info in zip(args.stl, module_names, infos):
            if info["strategy"] != "polyhedron":
                continue
            r = validate(stl_path, args.output, mod)
            if "error" in r:
                print(f"  {mod}: {r['error']}", file=sys.stderr)
            else:
                status = "PASS" if r["pass"] else "FAIL"
                print(f"  {mod}: Hausdorff = {r['hausdorff_mm']:.6f} mm  [{status}]",
                      file=sys.stderr)
                if not r["pass"]:
                    all_pass = False
        if all_pass:
            print("All parts within 0.1 mm target.", file=sys.stderr)
        else:
            print("WARNING: one or more parts exceed 0.1 mm tolerance.", file=sys.stderr)
            sys.exit(1)


if __name__ == "__main__":
    main()
